### ISSUE TITLE
Add Collection support

### ISSUE THREAD

**Issue by wildintellect** [developmentseed/sentinel1#1]
**Is your feature request related to a problem? Please describe.**
Current package only creates Items, we need to also generate a collection record for GRD.

**Describe the solution you'd like**
Add create_collection function, and matching tests.
Should allow for flexibility in HOST parameter.

**Comment by wildintellect** [comment]
Feature exists now on fork https://github.com/sharkinsspatial/sentinel1/tree/feat/grd_collection
TODO: Merge to main stactools-package fork?
Consider this done if we open a PR?
How does the kwargs_patch impact the the PR?

**Comment by jjfrench** [comment]
It's a friendly reminder that it hasn't been merged into the main packages. Is there still work to be done with the kwargs_patch?

**Comment by wildintellect** [comment]
@jjfrench sounded like no additional work but that the PR should start with the kwargs_patch (@sean), then a 2nd PR for the feat collection branch (@jjfrench)

**Comment by wildintellect** [comment]
kwargs is now merged
chore/template_upgrade is opened https://github.com/stactools-packages/sentinel1/pull/23 - a few conflicts to resolve?
then
feat/grd_collection should pull in chore/template_upgrade again to get latest changes and another PR opened.

**Comment by jjfrench** [comment]
I'll take a look at Pete's [comments](https://github.com/stactools-packages/sentinel1/pull/24#pullrequestreview-1275452637) and resolve them today

**Comment by jjfrench** [comment]
https://github.com/stactools-packages/sentinel1/releases/tag/v0.5.0 released 🥳
